[build]
  publish = "public"
  command = "hugo"

  [build.environment]
    HUGO_VERSION = "0.119.0"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"